import { MenuItem, Order, RiderProfile, Vendor } from './types';

export const CURRENT_CUSTOMER = {
  name: 'Nenman D.',
  phone: '0803 441 2290',
  address: 'No. 12 Tafawa Balewa Street',
};

export const CURRENT_VENDOR_ID = 'v1';

export const CURRENT_RIDER: RiderProfile = {
  id: 'r1',
  name: 'Chinedu Okoro',
  phone: '0814 902 1187',
  vehicle: 'Bajaj Boxer',
  plate: 'PL 482 KJ',
  rating: 4.92,
  trips: 1840,
};

export const VENDORS: Vendor[] = [
  {
    id: 'v1',
    name: 'Mama Cass Kitchen',
    category: 'food',
    neighborhood: 'Terminus',
    rating: 4.8,
    reviewCount: 612,
    deliveryMins: [20, 35],
    deliveryFee: 500,
    minOrder: 1500,
    commissionRate: 0.18,
    accent: '#FF5A36',
    description: 'Jollof, soups and grilled meats from a Terminus staple.',
    tags: ['Jollof', 'Soups', 'Grills'],
    isOpen: true,
    icon: 'restaurant',
  },
  {
    id: 'v2',
    name: 'Plateau Grill House',
    category: 'food',
    neighborhood: 'Rayfield',
    rating: 4.7,
    reviewCount: 388,
    deliveryMins: [25, 40],
    deliveryFee: 600,
    minOrder: 2000,
    commissionRate: 0.18,
    accent: '#E04422',
    description: 'Suya, asun and chilled drinks near Rayfield.',
    tags: ['Suya', 'Asun', 'Drinks'],
    isOpen: true,
    icon: 'flame',
  },
  {
    id: 'v3',
    name: 'Bukuru Buka',
    category: 'food',
    neighborhood: 'Bukuru',
    rating: 4.6,
    reviewCount: 241,
    deliveryMins: [22, 38],
    deliveryFee: 550,
    minOrder: 1200,
    commissionRate: 0.16,
    accent: '#C2410C',
    description: 'Home-style swallow, stew and daily soups.',
    tags: ['Swallow', 'Stew', 'Local'],
    isOpen: true,
    icon: 'cafe',
  },
  {
    id: 'v4',
    name: 'Nenpan Rice Spot',
    category: 'food',
    neighborhood: 'Farin Gada',
    rating: 4.5,
    reviewCount: 190,
    deliveryMins: [18, 30],
    deliveryFee: 450,
    minOrder: 1000,
    commissionRate: 0.15,
    accent: '#EA580C',
    description: 'Fried rice, coconut rice and ofada plates.',
    tags: ['Rice', 'Ofada', 'Quick'],
    isOpen: true,
    icon: 'nutrition',
  },
  {
    id: 'v5',
    name: 'Fiditi Pharmacy',
    category: 'pharmacy',
    neighborhood: 'Angwan Rukuba',
    rating: 4.9,
    reviewCount: 420,
    deliveryMins: [15, 25],
    deliveryFee: 400,
    minOrder: 800,
    commissionRate: 0.1,
    accent: '#0EA968',
    description: 'OTC meds, first aid and wellness essentials.',
    tags: ['OTC', 'Wellness', 'First aid'],
    isOpen: true,
    icon: 'medkit',
  },
  {
    id: 'v6',
    name: 'Rayfield Health Plus',
    category: 'pharmacy',
    neighborhood: 'Rayfield',
    rating: 4.7,
    reviewCount: 176,
    deliveryMins: [18, 28],
    deliveryFee: 450,
    minOrder: 1000,
    commissionRate: 0.1,
    accent: '#059669',
    description: 'Prescriptions, baby care and vitamins.',
    tags: ['Baby', 'Vitamins', 'Rx'],
    isOpen: true,
    icon: 'fitness',
  },
  {
    id: 'v7',
    name: 'Terminus Chemist',
    category: 'pharmacy',
    neighborhood: 'Terminus',
    rating: 4.6,
    reviewCount: 133,
    deliveryMins: [12, 22],
    deliveryFee: 350,
    minOrder: 600,
    commissionRate: 0.09,
    accent: '#047857',
    description: 'Fast OTC pickup from the city centre.',
    tags: ['Pain relief', 'Cold', 'Skin'],
    isOpen: true,
    icon: 'pulse',
  },
  {
    id: 'v8',
    name: 'Shoprite-style Jos Mart',
    category: 'supermarket',
    neighborhood: 'Terminus',
    rating: 4.4,
    reviewCount: 890,
    deliveryMins: [35, 55],
    deliveryFee: 700,
    minOrder: 3500,
    commissionRate: 0.08,
    accent: '#2563EB',
    description: 'Groceries, household and fresh produce. Shopper-mode available.',
    tags: ['Groceries', 'Household', 'Fresh'],
    isOpen: true,
    icon: 'cart',
  },
  {
    id: 'v9',
    name: 'Farin Gada Market Run',
    category: 'supermarket',
    neighborhood: 'Farin Gada',
    rating: 4.3,
    reviewCount: 264,
    deliveryMins: [40, 70],
    deliveryFee: 800,
    minOrder: 2500,
    commissionRate: 0.07,
    accent: '#1D4ED8',
    description: 'Market shopping list fulfilled by a JozGo shopper.',
    tags: ['Market', 'Produce', 'Shopper'],
    isOpen: true,
    icon: 'basket',
  },
  {
    id: 'v10',
    name: 'Bukuru Superstore',
    category: 'supermarket',
    neighborhood: 'Bukuru',
    rating: 4.5,
    reviewCount: 310,
    deliveryMins: [30, 50],
    deliveryFee: 650,
    minOrder: 3000,
    commissionRate: 0.08,
    accent: '#1E40AF',
    description: 'Pantry staples, drinks and frozen foods.',
    tags: ['Pantry', 'Drinks', 'Frozen'],
    isOpen: true,
    icon: 'storefront',
  },
];

export const MENU: MenuItem[] = [
  // Mama Cass
  { id: 'm1', vendorId: 'v1', name: 'Jollof Rice & Chicken', description: 'Smoky party jollof with grilled chicken', price: 2800, section: 'Mains', inStock: true, icon: 'restaurant' },
  { id: 'm2', vendorId: 'v1', name: 'Pounded Yam & Egusi', description: 'Fresh poundo with rich melon soup', price: 3200, section: 'Mains', inStock: true, icon: 'restaurant' },
  { id: 'm3', vendorId: 'v1', name: 'Ofada Rice & Ayamase', description: 'Local rice with green pepper sauce', price: 3000, section: 'Mains', inStock: true, icon: 'leaf' },
  { id: 'm4', vendorId: 'v1', name: 'Beef Suya Platter', description: 'Spiced beef suya, onions and tomatoes', price: 2500, section: 'Grills', inStock: true, icon: 'flame' },
  { id: 'm5', vendorId: 'v1', name: 'Chapman', description: 'House chapman, extra citrus', price: 900, section: 'Drinks', inStock: true, icon: 'wine' },
  { id: 'm6', vendorId: 'v1', name: 'Zobo Ginger', description: 'Chilled hibiscus with ginger', price: 700, section: 'Drinks', inStock: true, icon: 'water' },

  // Plateau Grill
  { id: 'm7', vendorId: 'v2', name: 'Kilishi Mix', description: 'Dried spicy beef, 150g pack', price: 2200, section: 'Grills', inStock: true, icon: 'flame' },
  { id: 'm8', vendorId: 'v2', name: 'Asun Bowl', description: 'Peppered goat meat, extra heat', price: 3500, section: 'Grills', inStock: true, icon: 'flame' },
  { id: 'm9', vendorId: 'v2', name: 'Chicken Suya', description: 'Skewer of spicy chicken suya', price: 2400, section: 'Grills', inStock: true, icon: 'nutrition' },
  { id: 'm10', vendorId: 'v2', name: 'Heineken Can', description: 'Cold 33cl can', price: 1200, section: 'Drinks', inStock: true, icon: 'beer' },

  // Bukuru Buka
  { id: 'm11', vendorId: 'v3', name: 'Amala & Ewedu', description: 'With gbegiri and assorted meat', price: 2700, section: 'Swallow', inStock: true, icon: 'restaurant' },
  { id: 'm12', vendorId: 'v3', name: 'Eba & Okra', description: 'Draw soup with stockfish', price: 2500, section: 'Swallow', inStock: true, icon: 'restaurant' },
  { id: 'm13', vendorId: 'v3', name: 'White Rice & Stew', description: 'Tomato stew, two proteins', price: 2200, section: 'Rice', inStock: true, icon: 'nutrition' },

  // Nenpan Rice
  { id: 'm14', vendorId: 'v4', name: 'Coconut Rice', description: 'Coconut rice with turkey', price: 2600, section: 'Rice', inStock: true, icon: 'nutrition' },
  { id: 'm15', vendorId: 'v4', name: 'Fried Rice Combo', description: 'Fried rice, plantain and chicken', price: 2800, section: 'Rice', inStock: true, icon: 'restaurant' },
  { id: 'm16', vendorId: 'v4', name: 'Ofada Special', description: 'Ofada rice, sauce and boiled egg', price: 2900, section: 'Rice', inStock: true, icon: 'leaf' },

  // Fiditi Pharmacy
  { id: 'm17', vendorId: 'v5', name: 'Paracetamol 500mg (20)', description: 'Pain and fever relief tablets', price: 450, section: 'Pain relief', inStock: true, icon: 'medkit' },
  { id: 'm18', vendorId: 'v5', name: 'ORS Sachets (10)', description: 'Oral rehydration salts', price: 800, section: 'First aid', inStock: true, icon: 'water' },
  { id: 'm19', vendorId: 'v5', name: 'Vitamin C 1000mg', description: 'Immunity tablets, 30 count', price: 1800, section: 'Wellness', inStock: true, icon: 'fitness' },
  { id: 'm20', vendorId: 'v5', name: 'Antiseptic Cream 30g', description: 'Cuts, grazes and minor burns', price: 950, section: 'First aid', inStock: true, icon: 'bandage' },
  { id: 'm21', vendorId: 'v5', name: 'Cough Syrup 100ml', description: 'Adult dry cough formula', price: 1600, section: 'Cold & flu', inStock: false, icon: 'beaker' },

  // Rayfield Health Plus
  { id: 'm22', vendorId: 'v6', name: 'Prenatal Vitamins', description: '30-day maternal supplement', price: 4200, section: 'Wellness', inStock: true, icon: 'heart' },
  { id: 'm23', vendorId: 'v6', name: 'Baby Diapers M (32)', description: 'Mid-size tape diapers', price: 3800, section: 'Baby', inStock: true, icon: 'happy' },
  { id: 'm24', vendorId: 'v6', name: 'Ibuprofen 400mg', description: 'Anti-inflammatory, 20 tabs', price: 700, section: 'Pain relief', inStock: true, icon: 'medkit' },

  // Terminus Chemist
  { id: 'm25', vendorId: 'v7', name: 'Loratadine 10mg', description: 'Non-drowsy allergy tablets', price: 650, section: 'Allergy', inStock: true, icon: 'leaf' },
  { id: 'm26', vendorId: 'v7', name: 'Hydrating Lotion 200ml', description: 'Shea body lotion', price: 1400, section: 'Skin', inStock: true, icon: 'color-palette' },
  { id: 'm27', vendorId: 'v7', name: 'Multivitamin Gummies', description: 'Adult gummies, 60 count', price: 2500, section: 'Wellness', inStock: true, icon: 'nutrition' },

  // Jos Mart
  { id: 'm28', vendorId: 'v8', name: 'Indomie Carton (40)', description: 'Chicken flavour instant noodles', price: 7200, section: 'Pantry', inStock: true, icon: 'cube' },
  { id: 'm29', vendorId: 'v8', name: 'Peak Milk 900g', description: 'Fortified powdered milk', price: 4800, section: 'Dairy', inStock: true, icon: 'cafe' },
  { id: 'm30', vendorId: 'v8', name: 'Golden Penny Semo 1kg', description: 'Semolina swallow pack', price: 1450, section: 'Pantry', inStock: true, icon: 'nutrition' },
  { id: 'm31', vendorId: 'v8', name: 'Dettol 750ml', description: 'Antiseptic liquid', price: 2800, section: 'Household', inStock: true, icon: 'water' },
  { id: 'm32', vendorId: 'v8', name: 'Rice 10kg (Caprice)', description: 'Long grain parboiled rice', price: 14500, section: 'Staples', inStock: true, icon: 'cube' },
  { id: 'm33', vendorId: 'v8', name: 'Coca-Cola 50cl x12', description: 'PET pack of twelve', price: 3600, section: 'Drinks', inStock: true, icon: 'wine' },

  // Farin Gada Market
  { id: 'm34', vendorId: 'v9', name: 'Tomatoes (derica x4)', description: 'Fresh market tomatoes', price: 2800, section: 'Produce', inStock: true, icon: 'nutrition' },
  { id: 'm35', vendorId: 'v9', name: 'Onions (paint bucket)', description: 'Red onions, market measure', price: 2200, section: 'Produce', inStock: true, icon: 'ellipse' },
  { id: 'm36', vendorId: 'v9', name: 'Fresh Pepper Mix', description: 'Atarodo and tatase wrap', price: 1500, section: 'Produce', inStock: true, icon: 'flame' },
  { id: 'm37', vendorId: 'v9', name: 'Live Chicken', description: 'Medium broiler, cleaned on request', price: 6500, section: 'Protein', inStock: true, icon: 'paw' },

  // Bukuru Superstore
  { id: 'm38', vendorId: 'v10', name: 'Frozen Turkey Wings 1kg', description: 'Imported turkey wings', price: 5200, section: 'Frozen', inStock: true, icon: 'snow' },
  { id: 'm39', vendorId: 'v10', name: 'Vegetable Oil 5L', description: 'Kings oil jerry can', price: 9800, section: 'Pantry', inStock: true, icon: 'beaker' },
  { id: 'm40', vendorId: 'v10', name: 'Indomie Hungry Man x5', description: 'Family pack noodles', price: 1800, section: 'Pantry', inStock: false, icon: 'cube' },
];

export const SEED_ORDERS: Order[] = [
  {
    id: 'JG-24018',
    vendorId: 'v1',
    vendorName: 'Mama Cass Kitchen',
    vendorCategory: 'food',
    customerName: 'Nenman D.',
    customerPhone: '0803 441 2290',
    neighborhood: 'Angwan Rukuba',
    address: 'No. 12 Tafawa Balewa Street',
    items: [
      { itemId: 'm1', name: 'Jollof Rice & Chicken', price: 2800, quantity: 1, icon: 'restaurant' },
      { itemId: 'm5', name: 'Chapman', price: 900, quantity: 2, icon: 'wine' },
    ],
    subtotal: 4600,
    deliveryFee: 850,
    discount: 0,
    total: 5450,
    paymentMethod: 'cash',
    status: 'on_the_way',
    createdAt: Date.now() - 1000 * 60 * 18,
    notes: 'Please call at the gate.',
    riderId: 'r1',
    riderName: 'Chinedu Okoro',
    riderPhone: '0814 902 1187',
    deliveryMode: 'point_to_point',
  },
  {
    id: 'JG-24012',
    vendorId: 'v5',
    vendorName: 'Fiditi Pharmacy',
    vendorCategory: 'pharmacy',
    customerName: 'Nenman D.',
    customerPhone: '0803 441 2290',
    neighborhood: 'Angwan Rukuba',
    address: 'No. 12 Tafawa Balewa Street',
    items: [
      { itemId: 'm17', name: 'Paracetamol 500mg (20)', price: 450, quantity: 2, icon: 'medkit' },
      { itemId: 'm19', name: 'Vitamin C 1000mg', price: 1800, quantity: 1, icon: 'fitness' },
    ],
    subtotal: 2700,
    deliveryFee: 400,
    discount: 0,
    total: 3100,
    paymentMethod: 'wallet',
    status: 'delivered',
    createdAt: Date.now() - 1000 * 60 * 60 * 26,
    notes: '',
    riderId: 'r1',
    riderName: 'Chinedu Okoro',
    riderPhone: '0814 902 1187',
    deliveryMode: 'point_to_point',
  },
];

export const PROMOS = [
  { code: 'JOZ200', title: '₦200 off first food order', subtitle: 'Min. ₦2,500 · Terminus & Rayfield', color: '#FF5A36' },
  { code: 'PHARM50', title: 'Free pharmacy delivery', subtitle: 'Orders above ₦3,000 today', color: '#0EA968' },
  { code: 'MARKET', title: 'Shopper runs from ₦700', subtitle: 'Farin Gada & Bukuru markets', color: '#2563EB' },
];
